### ISSUE TITLE
enquiry about json input and output

### ISSUE THREAD

**Issue by lchunleo** [pcdv/flak#1]
hi

 thanks for sharing your work. Could you share more about how to use the json as an input and output? thanks

**Comment by pcdv** [comment]
Hi,

First, you need to "install" JSON input and output converters into the App. This can be done by using the Jackson plugin:

    JacksonPlugin.install(app);

If you want the return value to be converted to JSON, just add the JSON annotation and return any JSON serializable object.

If you want your method to receive an argument automatically converted from JSON, add the JSON annotation and a method argument with the type you want to deserialize.

You can check out [this JUnit](https://github.com/pcdv/flak/blob/master/flak-tests/src/test/java/flask/test/JsonTest.java): the following method does both at the same time:

```java
  /**
   * Parses a JSON foo object and returns it.
   */
  @Put
  @Route("/api/foo")
  @JSON
  public Foo putFoo(Foo foo) {
    return foo;
  }
```

**Comment by lchunleo** [comment]
Thank you for your detailed explanation. 

Have you been considering to have a documentation on the design or maybe the functionality ? I seen you have quite a lot of features but need to a few read up to understand them. Though I had used flask before but still need some time to figure what how to use flak. It may be difficult for people for does not have flask background.

After trying exploring other micro web framework I find your very easy to learn and use and have good potential. It does.not have the cumbersome of other software which use maven to setup or many third party software when the only intent is to get things running. Could you also elaborate more on the storage features ?

**Comment by pcdv** [comment]
Thanks.

It's true that documentation is lacking, I haven't had much time to spend on it and not many users to motivate me to write it :)

Do you have some specific features that you think should be documented first? It will be easier for me to focus on some use cases rather than write extensive documentation. Also, I'm not sure what you mean by "storage features".

**Comment by pcdv** [comment]
I added some documentation. Feel free to tell me what's missing. Closing this issue, you can create other ones for every piece of information that you feel should be added!
