### ISSUE TITLE
Deploying on github

### ISSUE THREAD

**Issue by HarshwardhanUmesh** [pcdv/flak#11]
can u please specify what the contents of Procfile might be

**Comment by pcdv** [comment]
Sorry, I'm not familiar with deployment on Github or Procfile so I can't help here. 

But flak is just a library that allows to generate a Java program with a main() method, so not very different from a "Hello World" application.

There is an example app at https://github.com/pcdv/flak-react-boilerplate that shows the command line.

**Comment by HarshwardhanUmesh** [comment]
Thanx sir
