### ISSUE TITLE
How to specify multiple inputs to test 

### ISSUE THREAD

**Issue by lchunleo** [pcdv/flak#2]
hi

 noted that i can input different parameters in the route and corresponding in the function. But what should i put for the url to test it out?

e..g.

@Post
@Route ("/functionname/:arg1/:arg2")
@InputFormat ("JSON")
public void functionname(int arg1, int arg2)

**Comment by pcdv** [comment]
Hi,

According to your route specification, a valid URL could be http://localhost:8080/functionname/123/456

Note that it is not mandatory to have the method name equal to the route prefix.

**Comment by lchunleo** [comment]
Thanks
