### ISSUE TITLE
No issue, just a question

### ISSUE THREAD

**Issue by WhiteHeadbanger** [pcdv/flak#6]
Hi.

Is it possible to interop flak with python? I was thinking of using java to build the GUI and python for server-side operations and database comms.
Yes, I could do it all in Flask directly, but my partner only knows java and I know python, and we wanted to create an app together, so that's why.

Thanks

**Comment by pcdv** [comment]
Hi

Unfortunately it is not possible. Flak (java) is inspired by Flask (python) but both play a similar role and are only for the backend side (server) of the app. You need to choose between java and python.

Cheers
