### ISSUE TITLE
How to add flak-backend-jdk to my classpath?

### ISSUE THREAD

**Issue by ZavierYang** [pcdv/flak#8]
Hi pcdv,

I'm new to the java development and want to try to use your flak. However, when I try to run the application, it will give me the error "Please add flak-backend-jdk to your classpath." 
I have tried to add the flak-backend-jdk folder in the classpath, but it didn't work. could you specify how to add this folder into classpath in Eclipse? Thank you.

![image](https://user-images.githubusercontent.com/61639419/141890824-0e85b57e-791e-4f40-b2e4-8ceaa1513b82.png)
![image](https://user-images.githubusercontent.com/61639419/141957545-c31ad75b-e4b3-4e45-acbb-18a4e851348f.png)

**Comment by pcdv** [comment]
Hi ZavierYang,

I see a lot of red in your screenshot. This means that dependencies are not correctly resolved in Eclipse.

I haven't used Eclipse in a long time so I can't help on the setup. You can try opening the project in Intellij IDEA, it will probably work better.

As this is not directly related to Flak, I'm closing the issue.

Cheers

**Comment by pcdv** [comment]
If you really want to use Eclipse, I seem to remember that you can add the eclipse gradle plugin in the root build.gradle then run gradlew eclipse to generate .project and .classpath files.

**Comment by ZavierYang** [comment]
Hi pcdv,

Thank you for your information. Since I never used Gradle before, I didn't import the project by Gradle (I didn't use Gradle because I have used your jflask and it can work without Gradle. Therefore, I thought this can import without Gradle as well). 
After I studied about Gradle, the project can work now. Thanks.
